name: Feature Request
description: Suggest a new feature or enhancement for TRY-ON
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like to see... / A feature that allows...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered... / Another approach could be...
    validations:
      required: false

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the application does this feature relate to?
      options:
        - Virtual Try-On / 3D Avatar
        - Product Recommendations
        - Size/Fit Calculator
        - User Interface / UX
        - Shopping / Checkout
        - Integration (Shopify, etc.)
        - AI / Emotional Companion (Pau)
        - Performance / Speed
        - Other
      default: 8
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Would significantly help
        - Critical - Blocking my use of the app
      default: 1
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / User Story
      description: Describe a specific scenario where this feature would be useful.
      placeholder: As a [type of user], I want to [goal] so that [benefit]...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have mockups, screenshots, or examples from other apps, please share them here.
      placeholder: Paste or drag images here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request here.
      placeholder: Any additional thoughts or considerations...
    validations:
      required: false
